# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Career.delete_all

Career.create(title: 'Communications Coordinator', name: 'Rosie', favorite:'I like being creative and trying new marketing campaigns. My favorite jobs are ones where everyone feels like their opinions and input matter.', skills: 'Writing & Editing, Communicating, Computer/technology (e.g. coding, digital design, CAD, Adobe, Excel, SPSS, etc.)', advice: "Think about what matters most to you and prioritize that when you apply to jobs. Examples: work-life balance, a good team, ability to be creative, etc.", education: "Bachelor's Degree", pay: '$61K - 90K', environment: 'Office', bookmark: false, hashtag: ["comms", "marketing", "social media"], image: 'Rosemary Grant.png')
Career.create(title: 'Electronic Resources Coordinator', name: 'Emalee', favorite:'Making someone feel happy at the library. Putting the perfect finishing touches on a website. Collaborating with coworkers.', skills: "Reading & Synthesizing, Communicating, Computer/technology (e.g. coding, digital design, CAD, Adobe, Excel, SPSS, etc.)", advice: "Librarianship is a satisfying career and you can take a wide variety of paths to get there. If you're smart, always curious, and happy helping others, this could be a great profession for you. Libraries are a cornerstone of civilization that bring immense value to the world!", education: "Master's Degree", pay: '$61K - 90K', environment: 'Library', bookmark: false, hashtag: ["tech", "librarian", "education"], image: 'Kee Space.png')
Career.create(title: 'Senior Corporate Relations Officer', name: 'Meghan', favorite:'Creating impactful relationships. My coworkers and partners are all intelligent, passionate, and driven by purpose. It is magic when you can work together to create a powerful program that does good for the world.', skills: "Writing & Editing, Reading & Synthesizing, Communicating", advice: "Competition for sustainability jobs is fierce. Explore majors that are high in-demand (like fundraising or communications) because those will still allow you to get a job with purpose. Also, get internships/jobs at different types of organizations see if you prefer a startup vibe or a well-established organization.", education: "Bachelor's Degree", pay: '$90K', environment: 'Office', bookmark: false, hashtag: ["relations", "management", "business", "sustainability"], image: 'Meghan Ball.jpg')
Career.create(title: 'VP Business Intelligence and Analytics', name: 'Judi', favorite:'Creating new ways of looking at the business. Discovering insights that increase sales and growth.', skills: "Communicating, Analyzing & Applying logic, Hard Math (e.g. carrying out calculations, coding)", advice: "Be curious. Ask questions. Get comfortable with math and persevering through solving tough problems.", education: "Bachelor's Degree", pay: '$121K +', environment: 'Office/Home', bookmark: false, hashtag: ["business", "data", "science", "math", "analytics"], image: 'Judith Breisch.jpg')
Career.create(title: 'Architectural Designer', name: 'Andrea', favorite:'Creating something and seeing it built.', skills: "Communicating, Computer/technology (e.g. coding, digital design, CAD, Adobe, Excel, SPSS, etc.)", advice: "Find an office that does the kind of work you find interesting. Seek out opportunities to explore the different jobs within architecture like programming, concept design, project management, etc.", education: "Bachelor's Degree", pay: '$61K - 90K', environment: 'Office', bookmark: false, hashtag: ["math", "design", "art", "architecture"], image: 'Andrea Martinez.jpg')
Career.create(title: 'Senior Director of Marketing', name: 'David', favorite:'The incredible strength and collaboration of the travel and tourism industry. Tourism and hospitality professionals are some of the most welcoming people. Even competitors are willing to help each other!', skills: "Writing & Editing, Communicating, Creatively designing", advice: "Always be curious and open to learning new things. Communication, collaboration and creating connections are key.", education: "Bachelor's Degree", pay: '$61K - 90K', environment: 'Office', bookmark: false, hashtag: ["marketing", "comms", "tourism", "tech", "business"], image: 'David Breisch.jpg')
Career.create(title: 'Eye Surgeon', name: 'Mike', favorite: 'Operating. It is stimulating and rewarding. There are always new techniques and devices to learn or develop.', skills: "Communicating, Attention to detail, Hand-eye coordination", advice: "It's a long road. Work smart and enjoy yourself along the way.", education: 'Special track (includes med/vet school, residency, fellowship)', pay: '300-500K', environment: "Private clinic and surgery center", bookmark: false, hashtag: ["surgery", "doctor", "science", "medicine"], image: 'Michael Henry MD.jpg')
Career.create(title: 'Doctor of Audiology Resident', name: 'Luke', favorite:"I love providing re/habilitation for individuals with hearing loss, especially children. I love seeing a kids' performance in school and life improve when they have appropriate access to language. I also favor working with the Deaf population -- I'm fluent in American Sign Language!", skills: "Writing & Editing, Research & Experimentation, Communicating", advice: "An aspiring audiologist should be passionate about education, communication and language access. It takes years to obtain the Doctor of Audiology (Au.D.), which is a clinical doctorate degree. In total, the young person can expect themselves to be in college for a total of 7-8 years and have many clinical rotations, including a residency.", education: 'Special track (includes med/vet school, residency, fellowship)', pay: '$61K - 90K', environment: 'Hospital', bookmark: false, hashtag: ["doctor", "pediatrics", "ASL", "deaf", "language"], image: 'Luke Hinson.jpeg')
Career.create(title: 'Personal Trainer & Nutrition Coach', name: 'Coach Brandon', favorite:"Building relationships, changing lives, and being able to workout myself in my spare time.", skills:"Communicating, Understanding human behavior, Physical fitness (e.g. strength, agility, flexibility)", advice: "Learn how to communicate and empathize with people.", education: 'GED/High School Diploma', pay: '$61K - 90K,', environment: 'Remote', bookmark: false, hashtag: ["trainer", "fitness", "education", "entrepreneur"], image: 'Brandon Woolfolk.jpeg')
Career.create(title: 'Emergency Medicine Physician', name: 'Ife', favorite: "I get to help someone feel better on their worst day. I love the instant gratification when I intervene successfully, plus the career is a good return on investment.", skills:"Reading & Synthesizing, Communicating, Analyzing & Applying logic, Applying hard knowledge of anatomy, physiology, and other medical basic science", advice: "Be resilient! Progression not perfection.", education: 'Special track (includes med/vet school, residency, fellowship)', pay: '$121K +', environment: 'Hospital', bookmark: false, hashtag: ["doctor", "science", "medicine"], image: 'Ife Adabonyan.jpg')
Career.create(title: "Business Systems Analyst", name: "William", favorite: "It's very satisfying to deliver projects that the clients are happy with and make their jobs better. I like the challenges of exceeding expectations and working with different teams.", skills: "Analyzing & Applying logic, Computer/technology (e.g. coding, digital design, CAD, Adobe, Excel, SPSS, etc.), Ability to multi-task or manage multiple projects at once", advice: "Find something that you like to do and are passionate about. Never stop learning and growing professionally. Look for opportunities, even during life changes and adversity.", education: "Bachelor’s Degree", pay: "$121K +", environment: "Remote/Home Office", bookmark: false, hashtag: ["business", "data", "math", "analytics"], image: "PaulH.jpg")
Career.create(title: "Attorney", name: "Benjamin", favorite: "I love cases that need cracking. After discussions & arguments with my coworkers, we figure out together how the law fits a scenario and how a statute/contract might be interpreted to help my client.", skills: "Writing & Editing, Reading & Synthesizing, Analyzing complex problems ", advice: "Lawyers deal with people on their worst days. The best solution to a case might not make people happy. Being ok with that will go a long way in becoming a successful lawyer.", education: "Juris Doctor (JD)", pay: "$91K - 120K", environment: "Office & Court", bookmark: false, hashtag: ["lawyer", "law", "court", "reading"], image: "Benjamin Ader.png")
Career.create(title: "Academic Advisor", name: "Jasmine", favorite: "The best part is getting to know students, and learning their strengths, weaknesses & goals. Helping students find their passions and achieve their goals is wonderful.", skills: "Communicating, Analyzing & Applying logic, Ability to work with multiple cultures and/or speak multiple languages", advice: "Your ability to connect with people on a personal level is key. This isn't a position that you should take 'just because'. The best and most impactful advisors realize that it cannot be a one-size-fits-all approach.", education: "Bachelor’s Degree, Master’s Degree", pay: "$61K - 90K", environment: "College Campus, some travel required", bookmark: false, hashtag: ["counseling", "education", "pscyhology"], image: "DarienG.jpg")
Career.create(title: "Therapist (Child/Family Trauma)", name: "Megan", favorite: "I love building empathic relationships with children & families and utilizing that for healing. It's exciting to draw from a wide range of therapies to provide clients with coping tools.", skills: "Communicating, Understanding human behavior, Creativity and flexibility", advice: "To be a competent social worker you have to be self-reflective and self-aware. Work on your own healing and regulation skills. You shouldn't ask a client to do something you haven't done (or aren't willing to do) yourself.", education: "Master's in Social Work", pay: "$61K - 90K", environment: "Office/Clinic", bookmark: false, hashtag: ["socialwork", "therapy", "psychology"], image: "Megan Henry.jpg")
Career.create(title: "Legislative Assistant (U.S. Senate)", name: "Olivia", favorite: "I love finding different ways to tackle policy problems: introducing legislation, encouraging federal agencies to take action, and working with stakeholders.", skills: "Writing & Editing, Reading & Synthesizing, Communicating", advice: "Networking (coffees and informational interviews) is crucial for most policy work. It allows you to position yourself for success. You never know who might be evaluating you for hire while you grab lunch.", education: "Bachelor’s Degree in Political Science", pay: "$91K - $121K +", environment: "Office", bookmark: false, hashtag: ["politics", "government", "relations"], image: "OliviaO.jpg")
Career.create(title: "Operations Director", name: "Dedra", favorite: "Ensuring that students and staff have access to essential items, as well as ensuring the school is operating efficiently.", skills: "Communicating, Analyzing & Applying logic, Ability to multi-task or manage multiple projects at once", advice: "In operations & alignment work, you must be passionate about serving people. This is a rewarding service role. You can take pride in ensuring that the staff, community and stakeholders feel supported.", education: "Bachelor’s Degree", pay: "$91K - 120K", environment: "School Building", bookmark: false, hashtag: ["operations", "management", "education"], image: "Dedra Adams-Johnson.jpg")
Career.create(title: "Doctor (Emergency Medicine)", name: "Eugene", favorite: "I enjoy teaching student and resident physicians. Working together as a team to save a life is always gratifying.", skills: "Communicating, Analyzing & Applying logic, Hard Science (e.g. applying knowledge of Biology/Physics/Chemistry)", advice: "Good grades are important but so is emotional intelligence and strong work ethic.", education: "English Bachelor's. Physiology and Biophysics Master's, Medical Track.", pay: "$200K+", environment: "Hospital", bookmark: false, hashtag: "[doctor, science, medicine]", image: "EugeneC.jpg")
Career.create(title: "Professional Development Specialist", name: "Kathryn", favorite: "As an extrovert, I love running trainings with 200+ people. Harnessing the energy of a crowd like that can be a lot of fun. Nothing brings me more joy than helping teachers improve for their students.", skills: "Research & Experimentation, Understanding human behavior, Ability to multi-task or manage multiple projects at once", advice: "Always build strong relationships with coworkers & bosses. Your next job will probably ask you for 3 references (coworkers who will sing your praises). Do you know who you would ask and what they would say about you?", education: "Bachelor's in Political Science/French and Master's in Education", pay: "$61K - 90K", environment: "Office, some travel required", bookmark: false, hashtag: ["education", "trainer", "operations"], image: "Breisch.jpg")
Career.create(title: "User Researcher", name: "Julia", favorite: "I love planning every detail of a study and strategizing how to apply our research conclustions to future products. I also love that this job allows me to make things better for users/visitors.", skills: "Reading & Synthesizing, Communicating, Understanding human behavior", advice: "User researchers come from a wide variety of college majors & experiences. Use that to your advantage! If you're always trying to figure out what makes people tick then you might be a good user researcher.", education: "Bachelor's in History, Master's in Museum Education", pay: "$61K - 90K", environment: "Office most days, some travel required", bookmark: false, hashtag: ["data", "research", "psychology", "museum"], image: "CathyS(julia).jpg")
Career.create(title: "Intuitive Guide", name: "Harumi", favorite: "There's magic that happens when people learn how access and heed their own inner wisdom! I love showing people ways to listen to their intuition and let go of baggage.", skills: "Writing & Editing, Communicating, Understanding human behavior", advice: "Notice when something feels 'off' or 'not right' in your mind or body. Learning to pay attention to the signals our body and inner wisdom send us is key to guiding ourselves and others on the journey.", education: "Bachelor's in English and Creative Writing; Music; Master's in Nonprofit Leadership", pay: "$91K - 120K", environment: "Home office", bookmark: false, hashtag: ["intuition", "counseling", "education", "psychology", "entrepreneur"], image: "HarumiL.jpg")
Career.create(title: "Program Analyst", name: "Dylan", favorite: "I love problem solving & thinking creatively: how data can be used to ensure each student is receiving support they need, when they need it, and how they need it. Plus, being able to create change across the country.", skills: "Communicating, Computer/technology (e.g. coding, digital design, CAD, Adobe, Excel, SPSS, etc.), Ability to multi-task or manage multiple projects at once", advice: "Lean into story telling. What stories are the data showing and how can you share that with others? The ability to communicate effectively sharing a story is priceless.", education: "Bachelor's Degree Spanish/Psychology; 2 Master's Degrees in Counseling Psychology & Public Policy", pay: "$121K - 200K", environment: "Office", bookmark: false, hashtag: ["data", "math", "equity", "education", "government"], image: "Dylan Hart Medina.jpg")
Career.create(title: "Meetings Manager", name: "Kim", favorite: "I love bringing communities together, especially when it's people who are changing the world. I also get to visit a lot of new countries and meet amazing people.", skills: "Communicating, Analyzing & Applying logic, Ability to multi-task or manage multiple projects at once", advice: "You have to learn how to be thorough and flexible. Situations are constantly in flux and you have to approach issues calmly with the latest data available.", education: "Bachelor's in Communication Studies & Philosophy", pay: "$61K - 120K", environment: "Office, some travel required", bookmark: false, hashtag: ["operations", "eventplanning"], image: "Kim Joyce.jpg")
Career.create(title: "Recruitment Manager", name: "Kaitlin", favorite: "Getting to spend every day working with, supporting, and being inspired by people who are committing their professional life to creating positive social and environmental change.", skills: "Communicating, Understanding human behavior, Ability to multi-task or manage multiple projects at once", advice: "Be curious and open to learning. 2 days are never the same; they're fast paced so be intentional about taking a breath every now and then! Also prioritize connecting with people.", education: "Bachelor's Degree", pay: "$61K - 90K", environment: "Office", bookmark: false, hashtag: ["relations", "business", "entrepreneur", "incubator"], image: "Kaitlin Capobianco.jpg")


User.delete_all
10.times do |i|
    User.create(name: "guest#{i+1}", username: 'guest', age: '15', interests: '[]', password: 'welcome', bookmarks: '[]')
end